disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length 
  - function_parameter_count
  - line_length
  - todo
  - trailing_whitespace
  - type_body_length
  - valid_docs
  - variable_name
excluded:
  - Pods
